device:
  name: tangorpro
  build_id: UQ1A.240105.002
  prev_build_id: UQ1A.231205.014

platform:
  product_makefile: device/google/tangorpro/aosp_tangorpro.mk

includes:
  - common/gen7pixel.yml

filters:
  overlay_files:
    prefix:
      # DockSetup itself is not shipped
      - DockSetup__auto_generated_rro_
